import Hero from "@/components/common/Hero";
import "./globals.css";
import Footer from "@/components/common/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Hero/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
